# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CameraParameters": "dataloader.ipynb",
         "KittiDataset": "dataloader.ipynb"}

modules = ["datasets/KITTI_Dataset.py"]

doc_url = "https://sakshamjindal.github.io/stereoVO/"

git_url = "https://github.com/sakshamjindal/stereoVO/tree/master/"

def custom_doc_links(name): return None
